[package]
name = "vimonga"
version = "0.0.1"
authors = ["notomo"]
edition = "2018"

[dependencies]
clap = "~2.32"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
mongodb = "0.3.12"
bson = "0.13.0"
failure = "0.1.5"
